import Link from "next/link";

export default function HeuristicSignalsPage() {
  return (
    <div className="page-shell">
      <header className="section-hero"><div><p className="eyebrow">RESEARCH MODULE · DISABLED</p><h1>Heuristic Signals</h1><p>Legacy opportunity and risk signals are excluded from the operating dashboard until their inputs are grounded in decoded onchain events.</p></div></header>
      <section className="panel disabled-module">
        <span className="method-chip">Not generated by default sync</span>
        <h2>Evidence before alerts</h2>
        <p>The current collector can prove that a transfer occurred. It cannot yet prove DEX direction, bridge intent, wallet profitability, or executable liquidity. Alerts depending on those claims remain disabled.</p>
        <ul><li>Use raw transfer and holder observations now</li><li>Decode transaction intent before assigning economic meaning</li><li>Backtest signal rules before publishing confidence</li><li>Keep missing inputs unavailable rather than zero</li></ul>
        <Link className="text-link" href="/opportunities">Open the descriptive Activity Lens →</Link>
      </section>
    </div>
  );
}
